schema:
  - pdl.graphql
  - https://pdl-api.dev.intern.nav.no/graphql:
      headers:
        Authorization: Bearer ${OBO_TOKEN}
        Behandlingsnummer: {$BEHANDLINGS_NUMMER}
documents: '*.graphql'
